### PR TITLE
#26 - Fix style prop

### LINKED ISSUE #26: Element style is not set
`<Comp style={{ display: 'block' }} />` will not set the `display` to `"block"`; it will be `undefined`.

### PR DESCRIPTION
**Pull request by treshugart**
Fixes #26.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -55,6 +55,8 @@ export default function (CustomElement, opts) {
 
         if (name.indexOf('on') === 0) {
           syncEvent(node, name.substring(2), props[name]);
+        } else if (name === 'style') {
+          node.setAttribute('style', props[name]);
```
Comment (bradleyayers) [inline src/index.js]: Interesting, so React transforms `style={{ display: 'block' }}` to CSS?

Comment (stevemao) [inline src/index.js]: Do we care about `ref` and `className`, etc?

**Comment by joscha** [comment]
LGTM

File: src/index.js (hunk 1 above)
Comment (treshugart) [inline src/index.js]: @stevemao I added a test for `className` to ensure that works.

@bradleyayers it seems React actually doesn't do that. I was getting a false positive. Instead I decided to just pass-through style but we needed to make sure it was being passed as the `attrs` argument to `React.createElement()` for the test to pass.

File: src/index.js [hunk 2]
```diff
@@ -61,7 +62,7 @@ export default function (CustomElement, opts) {
       });
     }
     render() {
-      return React.createElement(tagName, null, this.props.children);
+      return React.createElement(tagName, { style: this.props.style }, this.props.children);
```
Comment (stevemao) [inline src/index.js]: What about `{...this.props}`?

Comment (joscha) [inline src/index.js]: Would be transpiled to a call that contains `Array.from`. One of our mobile browsers we need to support doesnt know that yet if I remember correctly.

Comment (treshugart) [inline src/index.js]: @joscha that's for objects.

@stevemao It's still in TC39 [stage 2](https://github.com/tc39/proposals). I'll add a test since it's common practice in React, but I'll note that there's no special behaviour necessary for this so we're essentially testing Babel here.

Comment (stevemao) [inline src/index.js]: @treshugart Yup sorry
What about `{this.props}`. Can we just pass all props down without explicitly listing everything?

File: src/index.js (hunk 1 above)
Comment (treshugart) [inline src/index.js]: @bradleyayers Discussed IRL, but for posterity:

- React enforces you pass a style object that maps to a [CSSStyleDeclaration](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration).
- We use `willReceiveProps()` to set properties on the element. In this lifecycle callback, `style` is passed in as an object.
- We must pass the `style` prop to `React.createElement()` as `attributes` in order for React to apply its special behaviour to it (i.e. converting to a string and numbers have `px` appended to them.

File: src/index.js (hunk 2 above)
Comment (treshugart) [inline src/index.js]: Yeah, you can just do `<Element {...this.props} />` and everything will get set through our `willReceiveProps()` callback (which is what we use to ensure props are set as properties on the web component).

Comment (stevemao) [inline src/index.js]: I mean here instead of 
```js
return React.createElement(tagName, { style: this.props.style }, this.props.children);
```

Is there any downside to just simply
```js
return React.createElement(tagName, { this.props }, this.props.children);
```

Comment (treshugart) [inline src/index.js]: That'll set attributes instead of properties.

**Comment by treshugart** [comment]
lgtm
